#!/bin/zsh

ltsv_awk_script=$(cat <<-'EOS'
function key(name) {
    for (i = 1; i <= NF; i++) {
        match($i, ":");
        xs[substr($i, 0, RSTART)] = substr($i, RSTART+1);
    };
    return xs[name":"];
}
EOS
)
awk -F'\t' "${ltsv_awk_script} ${@}"
